services:
  db:
    image: docker.io/library/postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: example

  web:
    image: docker.io/library/nginx:latest
    depends_on:
      - db
    volumes:
      - web-config:/etc/nginx/conf.d
    networks:
      - backend
      - frontend
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host

volumes:
  db-data:
  web-config:

networks:
  backend:
  frontend:
